nodes:
  - id: bbox_min_lon
    ref: inputs.bbox_min_lon
  - id: bbox_min_lat
    ref: inputs.bbox_min_lat
  - id: bbox_max_lon
    ref: inputs.bbox_max_lon
  - id: bbox_max_lat
    ref: inputs.bbox_max_lat
  - id: max_cloud_cover
    ref: inputs.max_cloud_cover
  - id: stac_query
    ref: models.stac_query
  - id: stac_items
    ref: outputs.stac_items
edges:
  - from:
      id: bbox_min_lat
    to:
      id: stac_query
      port: bbox_min_lat
  - from:
      id: bbox_min_lon
    to:
      id: stac_query
      port: bbox_min_lon
  - from:
      id: bbox_max_lat
    to:
      id: stac_query
      port: bbox_max_lat
  - from:
      id: bbox_max_lon
    to:
      id: stac_query
      port: bbox_max_lon
  - from:
      id: max_cloud_cover
    to:
      id: stac_query
      port: max_cloud_covery
