nodes:
  - id: bbox
    ref: inputs.bbox
  - id: max_cloud_cover
    ref: inputs.max_cloud_cover
  - id: stac_query
    ref: models.stac_query
  - id: output_stac_items
    ref: outputs.stac_items
edges:
  - from:
      id: bbox
    to:
      id: stac_query
      port: bbox
  - from:
      id: max_cloud_cover
    to:
      id: stac_query
      port: max_cloud_covery
  - from:  ## Important!! 
      id: stac_query  # From models - Source Node of the edge
      port: stac_items   #Output of the model described on the manifest
    to:
      id: output_stac_items # id of an existing node identifier from the list of the nodes above (⚠️ different from from.id)